### PR TITLE
Member Profiles Closes #586

### LINKED ISSUE #586: Member Profile Pages
I'm trying to make something like this over here: https://github.com/roryaronson/OpenFarm/tree/member-profiles

@simonv3 I scaffolded some of it and copy-pasted the `guides.index` into it and then the links to the Guides no longer worked. I fidgeted and added `@user` in front of `.guides.each` to make it work as much as it does. Not sure if that is the right thing to do. If you have a chance to check it out, that would be rad. I'm checking out for the weekend but am excited to pick this up again on Monday!

member profile 2

### PR DESCRIPTION
**Pull request by roryaronson**
This PR includes initial frontend work for 'member profile' pages. This consolidates the 'My Guides', 'My Gardens', and 'Account Settings' pages into one place for the member. It is also the beginnings of how members can interact with each other.

Things that are broken in this PR:
* Try deleting a Guide. It deletes it successfully but redirects the page to an error 
* The `devise/registrations/edit` partial doesn't work. Try uncommenting it and you'll see
* `/guides/index` isn't there anymore. Should we stub out something for Rails convention sake or should we redirect to the profile page?

Next Steps:
* Make the new 'Add Garden' button work and remove old confusing foo (lookout on Slack for a mockup of member signup flow)
* Displaying member badges
* Allow members to have a `favorite_crop` in the `user_settings` and display that Crop's image as their cover photo
* Allow members to upload a profile photo, and make/select a default one that isn't a barren field
* Follower/Following/Follow buttons? Explore/cinform what this concept even does and if we/members want such a thing
* Privacy controls
* Enable editing of the member profile

screenshot from 2015-04-07 00 35 03

screenshot from 2015-04-07 00 42 10

### CODE REVIEW

**Comment by simonv3** [comment]
I think instead of "Coming Soon" things we shouldn't mention them.

**Comment by roryaronson** [comment]
I agree. I meant this to be a work in progress. So maybe I should have not pushed to master, but instead to a member-profiles branch? Once we have the functionality we desire and the known bugs fixed, we can make it live.

**Comment by simonv3** [comment]
I'll work on this branch for a bit to get those tests working, as well as the controller stuff.

**Comment by simonv3** [comment]
I've moved this to a feature [here](https://github.com/openfarmcc/OpenFarm/tree/feature/member-profiles)

**Pull request closed without merging**
