### PR TITLE
Sitcky footer

### PR DESCRIPTION
**Pull request by warpling**

### CODE REVIEW

**Comment by simonv3** [comment]
@warpling can you update your branch so that it's mergeable without conflicts?

**Comment by warpling** [comment]
Sorry for the delay @simonv3, missed this notification. I'll get on it tomorrow.

**Comment by simonv3** [comment]
@warpling no worries!

**Comment by warpling** [comment]
I'm confused (I had a two `sticky-footer` branches >_<). Looks like you were able to update and merge this, correct?

**Comment by simonv3** [comment]
Nope! I haven't merged this. You had a branch a while ago that didn't work. This branch was supposed to fix it (and I think it did), there were just some changes to your docker file that I wasn't sure about, and I think you made another update that I hadn't tested yet.

**Pull request closed without merging**
