### PR TITLE
Actions are + modal styling

### PR DESCRIPTION
**Pull request by roryaronson**
Made sure it has proper margins/padding on mobile too

### CODE REVIEW

**Comment by roryaronson** [comment]
So the drag and drop doesn't want to work on mobile. (Touching and dragging just makes the whole page scroll). Maybe this is not a big deal right now, but eventually I think we'll need maybe Up/Down buttons fo

**Comment by roryaronson** [comment]
Woops!

As I was saying... up/down buttons to allow mobile users to switch up the ordering of the Actions.

**Comment by simonv3** [comment]
Yeah, I'm not surprised it doesn't work on mobile. Do you know if @RickCarlino got that working for farmbot? How does the rest of guide creation work on mobile for you by the way?

**Comment by roryaronson** [comment]
Pretty good actually! The only weird part are the buttons on bottom to advance steps. The green one always gets pushed onto another line which just looks off balance. I think we really just need to get rid of the 'cancel and go home' button.

**Comment by simonv3** [comment]
Yeah, we should probably remove that. I think fixing the back button will go some way to figuring that out.

**Pull request merged**
