### PR TITLE
Manual Upgrades

### PR DESCRIPTION
**Pull request by RickCarlino**
# What's New?

 * Remove Let's Encrypt gem in favor of Heroku's ACM
 * Upgrade some of the easier deps.
 * **This version is running on Heroku right now**.

### CODE REVIEW

**Comment by Br3nda** [comment]
There's a lotta ci failures.

There's a rubocop.yml added by @simonv3 that sets this repo code style to single quotes. Why change thise lines to use double?

**Comment by RickCarlino** [comment]
@Br3nda I've been slowly/incrementally converting stuff over to use `rufo` style defaults, as that's my personal preference. If you prefer single quotes, I can switch it back. As a side note, I don't think Simon participates in OpenFarm development any more.

**Comment by Br3nda** [comment]
Kei te pai. I've got the codeclimate from a D to a B with some ignores and rubocop fixes. Generally moving to consistent style and reducing complexity gonna make it easier to contribute

**Comment by RickCarlino** [comment]
Looks like the CI-error is just the integration tests being finicky. Merging. This is the version currently on production.

**Pull request merged**
