### PR TITLE
#912 - Restyle footer

### PR DESCRIPTION
**Pull request by simonv3**
Started working on #912 (though this doesn't close it). 

Things that still need to be done: 

* [ ] Add mailing list sign up form
* [ ] A nicer contact us email page 

Looks like so:

screenshot 2017-03-04 12 07 03

cc @sophiakc what do you have in mind for the "Call for Volunteers" page?

### CODE REVIEW

**Comment by roselynemakena** [comment]
Hi, @simonv3 I can see there's a pending PR, I am interested in working on this issue, has this been successfully closed?

**Comment by simonv3** [comment]
Hey @roselynemakena, it's not finished yet - please note the two todo items in the first comment on this PR. Feel free to work on this branch though, and commit directly to it - I don't think I'll have time in the next week to finish it.

**Comment by roselynemakena** [comment]
@simonv3 noted, working on the to do items. :)

**Comment by sophiakc** [comment]
Hey @simonv3 , I appreciate you have started working on that. Are there reasons behind some modifications from the initial wireframes? 
- size of titles
- Contribute, instead of Developer?
- About us, instead of About
- Slack group, instead of Join Slack
- FAQ before How it works
- Facebook icon type and 2nd instead of 1st
- Envelope icon removed besides to other icons, to go to the contact page (not for mailing list)
- email input box to subscribe for newsletter

Where is the contact page right now? What do you mean by nicer?

Have you checked the artboard on Figma to look for the attributes or have you only relied on the wireframe uploaded on Github?

**Comment by simonv3** [comment]
Hey @sophiakc 

For most of those I just haven't gotten around to them or wasn't paying attention. Also see my todo list in my PR comment.

**Comment by roselynemakena** [comment]
I am working on some of those issues @sophiakc

**Pull request merged**
