### PR TITLE
Issue #706 Fixed

### LINKED ISSUE #706: Limit the guide preview text in search results
Right now it displays the full text of the guide overview:
capture

_Edit by @simonv3_: 

This would be a great intro feature to add. Here's some steps to get started on this:

* [ ] Find where guides search results are located (hint, you're actually searching for a crop).
* [ ] Look for the nested guide view (`.html.erb`)
* [ ] There, find where the overview is printed out, and use a native Ruby method to limit the string text. There's actually some really clever ruby methods that will break on word, or on space, or on paragraph. Play around and figure out what looks good. 
* [ ] Commit your changes on git and do a pull request
* [ ] Sit back and enjoy a warm beverage (or a cool one if you're in warmer climates!). You did a good deed :).

### PR DESCRIPTION
**Pull request by TheChirpyWitch**
#706 Issue Fixed.

### CODE REVIEW

**Comment by simonv3** [comment]
Hey @TheChirpyWitch. This looks great, but you'll have noticed that the CI failed. This looked like it was timeout errors, so I just ran it again, and everything looks rosy. 

Thanks for writing this PR. It's a small thing but it's much appreciated. It will make things much more browseable :)

**Comment by TheChirpyWitch** [comment]
Hey! Please close this issue.

**Comment by roryaronson** [comment]
Got it ;)

**Comment by simonv3** [comment]
Fun fact, if you use "close #<issue-number>" in the commit message github will automatically close the issue for you! I think it has to be <verb> <issue-number>, and not <issue-number> <verb> like you had.

**Pull request merged**
