### PR TITLE
Use generic crop icon when specific crop icon does not exist - fix #926

### LINKED ISSUE #926: Use generic crop icon when specific crop icon does not exist
@simonv3 has started to display the crop icons across the frontend. See the first peek under "Companion Plants" for [Kale](https://openfarm.cc/en/crops/kale)! 

screen shot 2017-04-24 at 4 07 59 pm

But its pretty ugly when there is no icon available:
screen shot 2017-04-24 at 4 09 37 pm

So we can use [this generic crop icon](https://drive.google.com/file/d/0Bzm0yyP7JMLicmZIM3cycWFlQ0E/view?usp=sharing) whenever this is the case.
screen shot 2017-04-24 at 4 12 32 pm

### PR DESCRIPTION
**Pull request by jeffcore**
Fix for the broken crop image: 

- Added the generic-crop.svg file to /app/assets/images
- Added the function load_generic_plant_icon to the application_helpers.rb file, this loads the svg as a html escaped text file
- Added helper:all to the app/controllers/application_controller.rb file, this give us the ability to access the helper functions in the project
- Changed the crop/show view the conditional statement to look for an empty image and run the load_generic_plant_icon function

I tested everything, let me know if I need further changes.

### CODE REVIEW

**Comment by simonv3** [comment]
Awesome, thanks for the PR @jeffcore! I've asked @RickCarlino to review it too. I'm not super familiar on making your own helpers, so I think you're way ahead of me. He's a bit more of a Ruby/Rails expert.

**Comment by jeffcore** [comment]
Thanks for the help.

**Comment by simonv3** [comment]
Awoo! I'll do a deploy now :)

**Comment by roryaronson** [comment]
Just tried this out - it looks great! Thanks @jeffcore for the contribution and the merge @simonv3 🥇

**Comment by jeffcore** [comment]
Thanks for hooking me up with my first OSS contribution.

**Pull request merged**
