### PR TITLE
fix title on edit guide page to say 'Edit' instead of 'Create'

### PR DESCRIPTION
**Pull request by rjmccluskey**
In response to Issue #513 

The same template (_new_guide_steps.html.erb) was being used for creating a new guide AND for editing an existing guide. To fix this, a local variable 'edit' is passed to the template when it is rendered for editing. When edit = true, a different title is given which says 'Edit A Growing Guide'

### CODE REVIEW

**Comment by simonv3** [comment]
Thanks for the PR @rjmccluskey! We know that they're the same, but at the moment the functionality shared between the two is pretty much identical. Once they start diverging a bit more (beyond this one if/else statement so far) we'll probably break them out into different pages.

(just to explain the current situation)

Before I pull this in, could you add a english language instance `.edit_a_growing_guide` in `en.yml`?

**Comment by rjmccluskey** [comment]
Added :)

**Comment by roryaronson** [comment]
Glad to see you're up and running @rjmccluskey! Thanks for the PR

**Comment by simonv3** [comment]
Sorry, meant to pull this in a couple of days ago!

**Comment by rjmccluskey** [comment]
Woo! My first PR to OpenFarm! haha no worries @simonv3

**Pull request merged**
