### PR TITLE
Fix issue # 859

### PR DESCRIPTION
**Pull request by nicholasedwards**
Hi, farming friends! I am a noob here. This is my very first attempt at an open-source pull request!

On the front page, I replaced the big openfarm logo with the call to action "Grow Your Food". I changed the following text to "Farm and garden through knowledge sharing".

I moved the logo to the top left corner of the page. On the front page, the logo is not clickable, but in the same spot on other pages, the logo is clickable and links to the front page.

I also noticed that the logo on the other pages had blurrier edges than the logo which was on the front page. So, I deleted the blurry image file, and the higher-resolution image is now used throughout the app.

### CODE REVIEW

**Comment by simonv3** [comment]
Awesome. Thanks for the contribution @nicholasedwards! This looks great, and you'll see I have merged it in. You'll be able to see it on staging in a couple of minutes: http://staging.openfarm.cc

Super flattered that this is your first Open Source contribution! Your PR was very thorough and much appreciated! :)

**Comment by sophiakc** [comment]
Wow super efficient @nicholasedwards, that's great!

**Comment by nicholasedwards** [comment]
Thanks!

**Comment by sophiakc** [comment]
Suggested improvements:
- make the logo bigger: screen shot 2016-11-25 at 12 38 52
- on the front page, the logo could be clickable and refresh the page

**Comment by simonv3** [comment]
Hey @sophiakc could you make a new ticket for this? Thanks!

**Comment by nicholasedwards** [comment]
@sophiakc Thanks for the improvements. I'll make these changes soon!

**Comment by nicholasedwards** [comment]
@sophiakc @simonv3 alrighty, I implemented these suggested improvements and made a new pull request. PR #866. Woohoo!

**Comment by simonv3** [comment]
:thumbsup:

**Pull request merged**
