### PR TITLE
Fixed Issue #809

### PR DESCRIPTION
**Pull request by TheChirpyWitch**
This issue is only occurring when we call _add_to_gardens.html from a crop's guide, not when we call it from the crop itself. Meaning that there is some error in the view or functionality for 'add-to-gardens'. So I just commented some HTML as in here:
`<div class="add-to-garden center"> <!-- <% if current_user && current_user.confirmed? %> <div add-to-gardens crop-object=guide object-type="'guide'" user=currentUser> </div> <% end %> --> </div>`
And voila! It works. Still don't know why this was happening. My best guess is making the first div class 'add-to-garden' was somehow messing things up by rendering our addToGarden functionality.

### CODE REVIEW

**Comment by simonv3** [comment]
Hmm, I don't know if removing the functionality counts as fixing it!

**Comment by TheChirpyWitch** [comment]
The functionality is working. I think we were calling it twice.

**Comment by simonv3** [comment]
@TheChirpyWitch Is it still adding the guide you're growing the crop with?

**Comment by TheChirpyWitch** [comment]
Yeah, it's adding the guide too. And yes, I will have to resolve the merge conflict. Working on that now.

**Comment by simonv3** [comment]
Awesome, thanks! I'm not sure I understand the changes visually, so I'll pull it in and look locally :)

**Comment by simonv3** [comment]
Hey @TheChirpyWitch, in your text editor you can probably show an indicator for the 80th character down the side, which is where Hound calls that cut off. 

I'm seeing this when I bring this in: 
screenshot 2016-10-11 11 59 16

Which doesn't have the "Add Garden" dropdown anymore, which is the functionality I was expecting. How does adding this guide to my garden work now?

**Comment by TheChirpyWitch** [comment]
Try this: `<% if current_user %>
            <div add-to-gardens
              crop-object="guide"
              object-type="'guide'"
              user="currentUser">
            </div>
          <% end %>`
I was trying different things and I sort of forgot where it started working right. :/

**Comment by simonv3** [comment]
Uncommenting that line seems to make it work fine. Can you do that in this PR?

**Comment by simonv3** [comment]
Hey @TheChirpyWitch, are you still going to do this? (Totally fine if you don't have time, just want to know)

**Pull request closed without merging**
