### PR TITLE
Remove A Bit of Duplicate Code From the Show Guide Page

### PR DESCRIPTION
**Pull request by simonv3**
There's still quite a bit of duplicate content, because of the resized headers, but I'll have to poke around to better see about that.

### CODE REVIEW

**Comment by roryaronson** [comment]
Thanks for helping me out here Simon. I found it difficult to significantly change the layout for small screens without duplicate code in different ordering and with different styling. You have any thoughts?

**Comment by simonv3** [comment]
I'm not actually sure - I think it might have to involve some CSS trickery, and I'll have to dig a bit deeper.

**Comment by warpling** [comment]
I don't know what the common practice out there is for this, but I've done what you did before @roryaronson. I try to avoid it where possible (duplicate logic is more error prone, less likely to get fully tested, etc), but sometimes it does seem to be the best choice.

**Comment by simonv3** [comment]
As long as we thread carefully I think we'll be okay here. If someone knows better that comes along in the future, they can help us fix it :)

**Pull request merged**
