### PR TITLE
Hack to fix bug #542

### PR DESCRIPTION
**Pull request by dedesite**
-Manually define encrypted_password= method in models/user.rb. It's not the best solution but it works so far.

### CODE REVIEW

**Comment by dedesite** [comment]
Is it ok thiw way ?

**Comment by simonv3** [comment]
Hey @dedesite thanks so much for the PR!

@warpling, @RickCarlino and I spent a lot of time trying to debug this over the past week. The bug is something that is specific to certain mongoid installations, and most people don't seem to have a problem with it. Did you have the problem, and this fixed it?

@warpling, if you still have your broken version of mongoid lying around, could you test this?

**Comment by RickCarlino** [comment]
Hold on a sec- this might have some serious security implications.

Have you verified that this method doesn't call any hashing / salting functions? Will cryptographic functions be added to this method in future releases of mongoid / devise?

I don't like the idea of stubbing out method calls related to password encryption. I will take a look at the source code to make sure, but still, I really don't like the idea of patching a security related method in the name of hacking some dependency issues together.

**Comment by RickCarlino** [comment]
Source code for `encrypted_password=`:

```ruby
re_define_method("#{meth}=") do |value|
  val = write_attribute(name, value)
  if field.foreign_key?
    remove_ivar(field.metadata.name)
  end
  val
end
```

Looks like it doesn't have any safety implications, but patching this method still kind of scares me. I will double check the field in the database also to make sure we didn't miss anything.

**Comment by md5** [comment]
Chiming in from the peanut gallery here, I agree with Rick that a real fix
should be found.

**Comment by RickCarlino** [comment]
I'm still a bit worried about this idea because we're essentially patching security related code as a result of our inability to solve a dependency issue in development ENV. After looking into it, it looks like `encrypted_password` is being correctly set even with the patch applied, so there might not be any security concerns. On the flip side, it still makes me nervous to do this.

You guys can make a call on this one.

**Comment by warpling** [comment]
I have the same worries. This is great discovery for those of us trying to get our local versions working in the time being!…but we should probably keep this out of `master`.

**Comment by warpling** [comment]
Tried this on my local. It did eliminate the encrypted password errors, but I'm still not able to seed. Here's the beginning of my trace:

```
~/Code/OpenFarm () rake db:seed
rake aborted!
NoMethodError: undefined method `handler=' for #<Delayed::Backend::Mongoid::Job:0x007f99e78dcd08>
/Users/ryanmcleod/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:81:in `payload_object='
/Users/ryanmcleod/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:97:in `process_attribute'
/Users/ryanmcleod/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:25:in `block in process_attributes'
```

**Comment by dedesite** [comment]
Hello Guys,

I agree with you, this fix is hacky (hence the commit message) and we should find a better solution.
I tried to define encrypted_password in ```test/factories/users.rb``` but got the same problem...

I think the problem come from the fact I did a ```bundle update``` and got different versions of the gems. This might be the reason not everyone has this problem.

**Comment by simonv3** [comment]
There was a bit too much hesitation over this from some Ruby experts, so I'm going to close this PR for now. @dedesite, let me know if you're still having this problem. We should be able to find a better way to fix this.

**Comment by dedesite** [comment]
I did a fresh install of the project today and I don't have anymore the bug, so you can close everything related to it :).

**Comment by simonv3** [comment]
Yay! That's great to hear :)

**Pull request closed without merging**
