### PR TITLE
Fix/rspec

### PR DESCRIPTION
**Pull request by Br3nda**
Replaces #947 , which seems to be proposed into the wrong branch.

This is mostly work by @roselynemakena

### CODE REVIEW

**Comment by Br3nda** [comment]
There's heaps of layout changes in that branch -- do we want to have these merged?

**Comment by Br3nda** [comment]
@simonv3 I can fix up the tests/specs 8n the mainline, if you're ready to have these layout changes. But if I do that and layer decide you want the layout changes you're likely ro get lots of git conflicts to need resolving. Lemme know where you'd like me to work.

**Comment by simonv3** [comment]
Since this is @roselynemakena's work I don't want to make decisions for her. 

If you're happy making the test fixes on the main branch that would be awesome! Thanks for all the work you're putting in!

**Comment by roselynemakena** [comment]
Hi @Br3nda , yes please feel free to work on the branch. You are right, the layout changes particularly refer to issue #874 while #947 refers to wip changes to suit the new rspec tests affecting the layout changes.
Kindly assist to help resolve this, I have been quite held up in other projects..

**Comment by Br3nda** [comment]
closing.

**Pull request closed without merging**
