### PR TITLE
Fix bug #634 : check on img action existance before creating the stage

### PR DESCRIPTION
**Pull request by dedesite**
- Fix the bug but the overall new.js code need to be refactor IMHO.
- I'm not a Angular.js specialist so hope this is not wrong

It's maybe not a *real* fix but allows users to create guide again.

### CODE REVIEW

**Comment by dedesite** [comment]
It's not necessary since `!= null` handles both when value is `undefined` and when it's `null`.

It's for example the way coffeescript handle the `?` on a variable.

But if it's important for the project i'll send modified version.

**Comment by simonv3** [comment]
@dedesite I'm so sorry I haven't gotten to this sooner (been traveling) and have left you hanging like this.

The fix looks great. Hound can be a bit of a pain and obtuse sometimes, but it's great for whipping our code into a standard without having to nitpick every PR. Thanks for responding to it :).

**Comment by dedesite** [comment]
Hi Simon,

Sorry for responding so lately, I don't have much time for hacking these days...

I'm glad that the fix did the tricks, the overall code certainly need to be refactor cause it's obscure in this form. I'm not a big fan of Angular, maybe because I never get into it, it seems to be a very powerful tool but also difficult to master.

Anyway, I hope I can get more into OpenFarm development cause I really love the project and got a lot of ideas for it :).

**Comment by simonv3** [comment]
@dedesite The code has indeed slowly become a bit intense and obscure. I'd welcome any attempt at refactoring. I'll be doing some refactoring on the back-end myself this week.

I'm also happy experimenting with other frameworks. A couple of people have talked about ReactJS, and I've played with MithrilJS. If you see anywhere you think that could take a little refactoring and want to try something new, please do :)

**Comment by dedesite** [comment]
@simonv3 I'm quite unhappy with the current situation of the JS frameworks eco system. There are so many ! It's really difficult to choose a something which will keep the distance. I study a lot of framework in the past, everyone has a very specific approach and everyone was interesting in way but I really hope some kind of "consensus" will be found on how should we approach web app development.

Angular seems to be a good candidate because it's widely used but seems also very complicated.

I liked the simplicity of backbone, don't know if it's still actively develop.

As I say, I hope I'll have time to work on OpenFarm but right now I have other job to do.

Keep up good work.

**Pull request merged**
