### PR TITLE
Adjusted language + some style tweaks

### PR DESCRIPTION
**Pull request by roryaronson**

### CODE REVIEW

**Comment by simonv3** [comment]
The tests look for those specific strings, so that's probably why they failed.

**Comment by roryaronson** [comment]
Ah, I'll fix the tests and try running the test suite locally

**Comment by roryaronson** [comment]
Oh no, Hound is having a fit! I don't think I should fix any of this

**Comment by simonv3** [comment]
@roryaronson I'm going to see what I can do about tweaking the CSS hounding. It's a bit of a pain (I don't think we switched it on, it just decided for itself).

**Comment by roryaronson** [comment]
Please do! :dog2: ----> :poodle:

**Pull request merged**
