### PR TITLE
Missing semi-colons

### PR DESCRIPTION
**Pull request by Br3nda**
To improve the codeclimate score of this app, and generally make it more readable with consistent code style.

### CODE REVIEW

**Comment by Br3nda** [comment]
Travis is quite unhappy 

```
$ bundle install --jobs=3 --retry=3 --deployment
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
Bundler is unlocking ruby
You have added to the Gemfile:
* rubocop (~> 0.49.0)
```

**Comment by simonv3** [comment]
Hmm. Unfortunately I really don't have the time to look into this :/

**Comment by Br3nda** [comment]
I'm having a poke at it in my lunch break

**Comment by Br3nda** [comment]
Gemfile fix up is on #955

**Comment by Br3nda** [comment]
Can this be merged?

**Comment by simonv3** [comment]
Hey @Br3nda, merged it. I also made you part of the Contributors team. I think that means you'll be able to merge things yourself, and won't have to wait on me or someone else to merge things for you!

**Comment by Br3nda** [comment]
:tada: :balloon:  :D

**Pull request merged**
