### PR TITLE
(Draft) Icons endpoint

### PR DESCRIPTION
**Pull request by RickCarlino**
This is a first draft of an icons endpoint.

**Todo:**

 * Whatever Hound yells at me for
 * Coverage issues
 * Style
 * API convention compliance

**Questions**

 * The `Icon` model uses `SearchKick`. Do I need to run an index anywhere?

Other than that,  I think it will be good enough for what we're trying to do.

### CODE REVIEW

**Comment by simonv3** [comment]
Hey @RickCarlino, this looks great!

Though I'm a bit confused - I thought icons were specifically for crops. Is there mean to be a link between other objects (like crops) and icons? My understanding was that you'd attach icons to a crop somehow and not really that they could be created or searched for on their own. Or is that part of a future PR?

**Comment by RickCarlino** [comment]
(Whoops- looks like I broke CI- will investigate shortly)

@simonv3 As users of the OpenFarm API, we really only need the ability to retrieve/store/search icons at the moment (CC: @roryaronson if you have any thoughts on the matter). It would be nice to eventually link a crop to an icon, but right now, just storing them would be good enough for us as API consumers.

**Comment by roryaronson** [comment]
@RickCarlino I think we need to have them linked to a Crop on OF. How else would we know which crop the icon corresponds to on the FarmBot side? I was imagining we would search OF for a crop and grab all the associated data with it, including the icon.

We also need a way to upload the icons, which I imagined would happen just like photo uploading on the crop page. See #742

**Comment by RickCarlino** [comment]
@simonv3 Side note: Do you think these CI errors are caused by a missing index? It's bee na while since I've worked with SearchKick - is there is a standard place to put the `Icon.reindex` call?

**Pull request closed without merging**
