### PR TITLE
Update docker setup

### LINKED ISSUE #563: Get our docker file up to speed
@dnephin, you added it a while ago, did you get anywhere further with it. 

@guitsaru was saying he had some issues with getting ElasticSearch running in it. Since that's the main stumbling block for a lot of new developers to OF, that would be the ideal fix.

I'll try to see if I can get it running in the next week or so myself.

### PR DESCRIPTION
**Pull request by md5**
Fixes #563

### CODE REVIEW

**Comment by md5** [comment]
Lemme know if you'd like this as a single commit off a more recent base.

**Comment by simonv3** [comment]
I thought I had fixed that annoying bug.

**Comment by md5** [comment]
I'm surprised that RSpec doesn't a version of `eq` that takes an epsilon.

Looks like this module could be helpful, but I haven't used it myself: https://github.com/jimweirich/rspec-given

**Comment by simonv3** [comment]
@md5 Hmm, when I run the tests, I'm getting these failures: 
```
Failure/Error: Unable to find matching line from backtrace
     Faraday::ConnectionFailed:
       Failed to connect to 127.0.0.1 port 9200: Connection refused
```
Any thoughts?

**Comment by RickCarlino** [comment]
@md5 : Did you mean womething like this? https://www.relishapp.com/rspec/rspec-expectations/v/2-5/docs/built-in-matchers/be-within-matcher

**Comment by md5** [comment]
@simonv3 I'll take a look.

@RickCarlino That looks right! :+1:

**Comment by md5** [comment]
@simonv3 BTW, it might be good if you could tell me exactly how you're trying to run tests in Docker. I'm planning to test with `docker-compose run webapp bundle exec rake spec`.

**Comment by md5** [comment]
I've just pushed a couple commits that allowed `docker-compose run bundle exec rake spec` to pass for me.

The main thing I needed to do was make VCR ignore requests to port 9200 entirely. I also had the Dockerfile install `phantomjs` so that it doesn't have to be reinstalled into the container every time specs are run.

@simonv3 it's pretty odd that you're seeing failures involving port 9200 on 127.0.0.1. This is the failure I was seeing before I got the tests working locally:

```
       An HTTP request has been made that VCR does not know how to handle:
         GET http://search:9200/_aliases
```

**Comment by md5** [comment]
When it comes down to it, the fact that the Docker Compose setup has `volumes: ['.:/openfarm']` is going to make different behavior for different developers during `rake spec` almost inevitable.

**Comment by simonv3** [comment]
@md5 I was following your instructions in the `development.rst` file.

> Run `docker-compose up` to start a development environment
> Run `docker-compose run webapp bundle exec rake spec` to run the test suite

I just installed docker and docker compose via the instructions on the docker site. I'm on a mac, so I have to do the whole boot2docker thing first. 

How would  `volumes: ['.:/openfarm']` affect the set up? The docker-compose documentation isn't super clear on it. 

I'm getting the same error when just starting up the server:

```bash
docker-compose run webapp bundle exec rails s
```
with errors:
```log
/usr/local/bundle/gems/activesupport-4.0.2/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
=> Booting Thin
=> Rails 4.0.2 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/usr/local/bundle/gems/patron-0.4.18/lib/patron/session.rb:223:in `handle_request': Failed to connect to 127.0.0.1 port 9200: Connection refused (Faraday::ConnectionFailed)
	from /usr/local/bundle/gems/patron-0.4.18/lib/patron/session.rb:223:in `request'
	from /usr/local/bundle/gems/faraday-0.9.1/lib/faraday/adapter/patron.rb:33:in `call'
	from /usr/local/bundle/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/bundle/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/bundle/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
... etc
```

**Comment by md5** [comment]
I believe the issue is that it's picking up your `SEARCH_URL` setting setting from `config/app_environment_variables.rb`.

The way that `volumes: ['.:/openfarm']` affects the setup is by making it so that the developer's local directory (i.e. `.`) is directly mounted into the Docker container as `/openfarm`. This overwrites the contents of `/openfarm` as it was created during the container build, so that means that anything done to the default contents of `/openfarm` in the Dockerfile will be masked by the contents of the developer's local directory.

That being said, I think you would have the same problem if that `volumes` declaration were not there because whatever you have in your local `config/app_environment_variables.rb` will be copied into the image at build time. We could list that file in `.dockerignore` to avoid it accidentally being built into the image and probably should do so, but you'd still have the problem in the `docker-compose` case because it would still use your local copy.

@dnephin Any ideas? You have more experience with `docker-compose` than I do, being that you're a maintainer :+1:

**Comment by md5** [comment]
I'm guessing you have something like `ENV['SEARCH_URL'] = '127.0.0.1:9200'` in your `config/app_environment_variables.rb`. If so, changing that to `ENV['SEARCH_URL'] ||= '127.0.0.1:9200'` should work.

**Comment by simonv3** [comment]
Yep. The tests pass. Awesome!

However, I'm not 100% sure on how to get this running so that I can access the website on my own machine through the browser.

**Comment by md5** [comment]
@simonv3 Assuming you're using `boot2docker`, then you'll need to figure out the IP address of your VM with `boot2docker ip`. You should then be able to see the site at `http://192.168.59.XXX:3000/`.

**Comment by simonv3** [comment]
Looks like when I do docker-compose up, it shuts down again right away:
```
OpenFarm$ docker-compose up
Recreating openfarm_search_1...
Recreating openfarm_mongo_1...
Recreating openfarm_webapp_1...
Attaching to openfarm_search_1, openfarm_mongo_1, openfarm_webapp_1
search_1 | [2015-03-23 03:34:34,439][INFO ][node                     ] [Jackhammer] version[1.4.4], pid[1], build[c88f77f/2015-02-19T13:05:36Z]
search_1 | [2015-03-23 03:34:34,442][INFO ][node                     ] [Jackhammer] initializing ...
search_1 | [2015-03-23 03:34:34,452][INFO ][plugins                  ] [Jackhammer] loaded [], sites []
search_1 | [2015-03-23 03:34:39,694][INFO ][node                     ] [Jackhammer] initialized
search_1 | [2015-03-23 03:34:39,695][INFO ][node                     ] [Jackhammer] starting ...
search_1 | [2015-03-23 03:34:40,173][INFO ][transport                ] [Jackhammer] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.17.0.83:9300]}
search_1 | [2015-03-23 03:34:40,223][INFO ][discovery                ] [Jackhammer] elasticsearch/m3uk0fvtRuOFCTyUsWY19Q
search_1 | [2015-03-23 03:34:44,020][INFO ][cluster.service          ] [Jackhammer] new_master [Jackhammer][m3uk0fvtRuOFCTyUsWY19Q][535316dc3568][inet[/172.17.0.83:9300]], reason: zen-disco-join (elected_as_master)
search_1 | [2015-03-23 03:34:44,112][INFO ][http                     ] [Jackhammer] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/172.17.0.83:9200]}
search_1 | [2015-03-23 03:34:44,113][INFO ][node                     ] [Jackhammer] started
mongo_1  | mongod --help for help and startup options
mongo_1  | 2015-03-23T03:34:35.534+0000 [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=1b4e9c44a7f8
mongo_1  | 2015-03-23T03:34:35.534+0000 [initandlisten] db version v2.6.8
mongo_1  | 2015-03-23T03:34:35.534+0000 [initandlisten] git version: 3abc04d6d4f71de00b57378e3277def8fd7a6700
mongo_1  | 2015-03-23T03:34:35.534+0000 [initandlisten] build info: Linux build5.nj1.10gen.cc 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 BOOST_LIB_VERSION=1_49
mongo_1  | 2015-03-23T03:34:35.534+0000 [initandlisten] allocator: tcmalloc
mongo_1  | 2015-03-23T03:34:35.534+0000 [initandlisten] options: {}
mongo_1  | 2015-03-23T03:34:35.542+0000 [initandlisten] journal dir=/data/db/journal
mongo_1  | 2015-03-23T03:34:35.542+0000 [initandlisten] recover : no journal files present, no recovery needed
mongo_1  | 2015-03-23T03:34:35.559+0000 [initandlisten] waiting for connections on port 27017
search_1 | [2015-03-23 03:34:46,081][INFO ][gateway                  ] [Jackhammer] recovered [4] indices into cluster_state
webapp_1 | /usr/local/bundle/gems/activesupport-4.0.2/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
search_1 | [2015-03-23 03:34:52,414][INFO ][cluster.metadata         ] [Jackhammer] [crops_development_20150323033452188] creating index, cause [api], shards [5]/[1], mappings [_default_]
mongo_1  | 2015-03-23T03:34:52.691+0000 [initandlisten] connection accepted from 172.17.0.87:54161 #1 (1 connection now open)
search_1 | [2015-03-23 03:34:52,769][INFO ][cluster.metadata         ] [Jackhammer] [crops_development_20150323031153484] deleting index
search_1 | [2015-03-23 03:34:52,975][INFO ][cluster.metadata         ] [Jackhammer] [guides_development_20150323033452872] creating index, cause [api], shards [5]/[1], mappings [guide, _default_]
search_1 | [2015-03-23 03:34:53,365][INFO ][cluster.metadata         ] [Jackhammer] [guides_development_20150323031154170] deleting index
webapp_1 | A server is already running. Check /openfarm/tmp/pids/server.pid.
mongo_1  | 2015-03-23T03:34:54.075+0000 [conn1] end connection 172.17.0.87:54161 (0 connections now open)
webapp_1 | => Booting Thin
webapp_1 | => Rails 4.0.2 application starting in development on http://0.0.0.0:3000
webapp_1 | => Run `rails server -h` for more startup options
webapp_1 | => Ctrl-C to shutdown server
webapp_1 | Exiting
openfarm_webapp_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping openfarm_mongo_1...
Stopping openfarm_search_1...
```
And then when I `run webapp bundle exec rails s`:
```
OpenFarm$ docker-compose run webapp bundle exec rails s
/usr/local/bundle/gems/activesupport-4.0.2/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now
=> Booting Thin
=> Rails 4.0.2 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
A server is already running. Check /openfarm/tmp/pids/server.pid.
Exiting
```
`/openfarm/tmp/pids/server.pid` is empty on my own computer.

I try I running `docker-compose stop`:
```
Stopping openfarm_mongo_1...
Stopping openfarm_search_1...
```
But get the same error when I run `docker-compose run webapp bundle exec rails s`

**Comment by md5** [comment]
If you have a running `rails s` independent of Docker, then that `server.pid` file belongs to it. You'll need to stop your OpenFarm instance outside of Docker to get it to remove its own pid file.

If not, the pid file is leftover from some previous run and you can safely remove it with `rm tmp/pids/server.pid`.

When the logs inside the docker container refer to `/openfarm`, the `volumes` statement (along with a Virtualbox shared folder mount of `/Users`) is making that be a mounted copy of your local OpenFarm working directory.

So when it says `/openfarm/tmp/pids/server.pid`, that actually means something like `/Users/simon/path/to/OpenFarm/tmp/pids/server.pid`.

**Comment by md5** [comment]
It might be worth changing the default `rails s` command in the Dockerfile to use an alternate pidfile location, e.g. `-P tmp/pids/docker.pid`. I'll investigate a bit and send a PR if I get something good.

**Comment by simonv3** [comment]
Cool, removing the `server.pid` and then running `docker-compose up` seems to have worked, though it's pretty slow.

Thanks again!

**Comment by md5** [comment]
Happy to help! :+1: 

Any slowness should probably be expected. The performance of VirtualBox shared folders is abysmal, so when running with the default `RAILS_ENV=development` where things are being reloaded on change, you're not going to see great performance. This is a longstanding and acknowledged pain point of using Docker on a Mac, though there are a few labor-intensive workarounds to make performance better (e.g. using NFS instead of VirtualBox shared folders).

**Comment by dnephin** [comment]
@md5 I think what I would do is create a separate `docker-compose.yml` for testing (maybe `compose-testing.yml`), and a script to run the tests.  I'd include a `config/app_environment_variables.rb` specfically for the testing environment, so that everyone running the tests has the same config. It can either be added to the image (if the volume for the local code isn't being used), or just added as a second volume on top the code volume.

The test script would run compose with `-f compose-testing.yml -p openfarmtesting` (or the equivalent environment variables `COMPOSE_FILE` and `COMPOSE_PROJECT_NAME`), that way the containers being created will have a different name (the -p sets the project name), and they won't conflict with the dev environment containers.

There is some work in the docker-compose 1.2 release to be able to do this without duplicating much, but for now it's probably easier to just make a copy.

I'd be happy to submit a PR with this kind of setup, later in the week when I get some time, if you're interested.

**Pull request merged**
